"""Figure 11: Tier 2 cross-provider replication.
Spec-effect delta across 3 subjects × 2 response models, batteries generated by GPT-5.4.

Data source: DATA_REFERENCE.md §10, KEY_FINDINGS.md M9.

2026-04-22 revision: neutral descriptive title (interpretation moved to caption),
colorblind-safe palette + hatch redundancy, clearer x-axis label, paper-scale typography.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from pathlib import Path

FIG_DIR = Path(__file__).resolve().parents[1] / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

sns.set_theme(context='paper', style='whitegrid', palette='colorblind')
plt.rcParams.update({
    'font.size': 8.5,
    'axes.titlesize': 10,
    'axes.labelsize': 9,
    'legend.fontsize': 8,
    'xtick.labelsize': 8.5,
    'ytick.labelsize': 8,
})
CB = sns.color_palette('colorblind')
BLUE = CB[0]
ORANGE = CB[1]

subjects = ["Ebers", "Yung Wing", "Zitkala-Sa"]
sonnet_deltas     = [1.48, 1.91,  1.40]
gemini_pro_deltas = [1.07, 1.27, -0.55]

x = np.arange(len(subjects))
width = 0.35

fig, ax = plt.subplots(figsize=(8.5, 4.6))

bars1 = ax.bar(
    x - width / 2, sonnet_deltas, width,
    label="Sonnet (response model)", color=BLUE,
    edgecolor="black", linewidth=0.7,
)
bars2 = ax.bar(
    x + width / 2, gemini_pro_deltas, width,
    label="Gemini Pro (response model)", color=ORANGE,
    edgecolor="black", linewidth=0.7, hatch='//',
)

ax.axhline(y=0, color="black", linewidth=0.7)
ax.set_xlabel("Subject (Tier 2 replication set)")
ax.set_ylabel("Spec-effect Δ (points on 1-5 rubric)")
ax.set_title("Tier 2 cross-provider replication: spec-effect delta per subject × response model")
ax.set_xticks(x)
ax.set_xticklabels(subjects, fontsize=9)
ax.legend(loc="upper right", frameon=True, framealpha=0.92, edgecolor='#CCCCCC')
ax.grid(True, axis="y", alpha=0.3, linewidth=0.5)
ax.set_ylim(-1.0, 2.3)

for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        offset = 0.06 if height >= 0 else -0.06
        va = "bottom" if height >= 0 else "top"
        ax.text(
            bar.get_x() + bar.get_width() / 2, height + offset, f"{height:+.2f}",
            ha="center", va=va, fontsize=8, fontweight="bold",
        )

# Small note on battery source
ax.text(0.5, -0.18,
        'Batteries generated by GPT-5.4 (non-Anthropic). Baseline per cell: C5 score for that subject × model.',
        transform=ax.transAxes, ha='center', va='top',
        fontsize=7, color='#444', fontstyle='italic')

plt.tight_layout()
outfile = FIG_DIR / "fig11_tier2_replication.png"
plt.savefig(outfile, dpi=300, bbox_inches="tight", facecolor="white")
print(f"Wrote: {outfile}")
