"""Figure 11: Tier 2 cross-provider replication.
Spec-effect delta across 3 subjects × 2 response models, batteries generated by GPT-5.4.

Data source: DATA_REFERENCE.md §10, KEY_FINDINGS.md M9.
"""

import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

FIG_DIR = Path(r"C:\Users\Aarik\Anthropic\memory-study-repo\figures")
FIG_DIR.mkdir(parents=True, exist_ok=True)

subjects = ["Ebers", "Yung Wing", "Zitkala-Sa"]
sonnet_deltas = [1.48, 1.91, 1.40]
gemini_pro_deltas = [1.07, 1.27, -0.55]

x = np.arange(len(subjects))
width = 0.35

fig, ax = plt.subplots(figsize=(10, 5.5))

bars1 = ax.bar(
    x - width / 2,
    sonnet_deltas,
    width,
    label="Sonnet (response model)",
    color="#2980b9",
    edgecolor="black",
    linewidth=1.2,
)
bars2 = ax.bar(
    x + width / 2,
    gemini_pro_deltas,
    width,
    label="Gemini Pro (response model)",
    color="#27ae60",
    edgecolor="black",
    linewidth=1.2,
)

ax.axhline(y=0, color="black", linewidth=1)
ax.set_ylabel("Spec-effect Δ (points on 1-5 rubric)", fontsize=11)
ax.set_title(
    "Tier 2 cross-provider replication: spec direction holds in 5 of 6 cells\n"
    "Batteries generated by GPT-5.4 (non-Anthropic)",
    fontsize=12,
)
ax.set_xticks(x)
ax.set_xticklabels(subjects, fontsize=11)
ax.legend(loc="upper right", fontsize=10)
ax.grid(True, axis="y", alpha=0.3)
ax.set_ylim(-1.0, 2.3)

for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        offset = 0.06 if height >= 0 else -0.06
        va = "bottom" if height >= 0 else "top"
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            height + offset,
            f"{height:+.2f}",
            ha="center",
            va=va,
            fontsize=10,
            fontweight="bold",
        )

plt.tight_layout()
outfile = FIG_DIR / "fig11_tier2_replication.png"
plt.savefig(outfile, dpi=300, bbox_inches="tight", facecolor="white")
print(f"Wrote: {outfile}")
